---
# v2022.01

# If `envsubst` command is available, environment variables can be used in this file.

ssh:
  key: ~/.ssh/id_rda
  host: example.com
  port: 22
  user: johndoe
path:
  source: /tmp/
  remote: tmp/

rsync:
  # https://download.samba.org/pub/rsync/rsync.1#opt--info
  #   backup     Mention files backed up
  #   copy       Mention files copied locally on the receiving side
  #   del        Mention deletions on the receiving side
  #   flist      Mention file-list receiving/sending (levels 1-2)
  #   misc       Mention miscellaneous information (levels 1-2)
  #   mount      Mention mounts that were found or skipped
  #   name       Mention 1) updated file/dir names, 2) unchanged names
  #   progress   Mention 1) per-file progress or 2) total transfer progress
  #   remove     Mention files removed on the sending side
  #   skip       Mention files that are skipped due to options used
  #   stats      Mention statistics at end of run (levels 1-3)
  #   symsafe    Mention symlinks that are unsafe
  #
  #   all        Set all options (e.g. all4)
  #   none       Silence all options (same as all0)
  info:
    - progress2
    - stats1
