---

name: Lint

"on":
  create:
  pull_request:
  push:
    branches: ['*']
  workflow_dispatch:

jobs:

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo -n 'exec find . -maxdepth 2 -name .git -type d -prune -o -type f ' > ci_shellcheck.sh
          echo -n '\( -name \*.sh -or -name \*.bats -or -name \*.bash \) -print0 ' >> ci_shellcheck.sh
          echo -n '| xargs -0 -r -n1 shellcheck ' >> ci_shellcheck.sh
          echo -n '--enable=all --severity=warning --color=never --format gcc' >> ci_shellcheck.sh
      - uses: docker://pipelinecomponents/shellcheck:latest
        with:
          args: /bin/sh ci_shellcheck.sh

  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pipelinecomponents/yamllint:latest
        with:
          args: yamllint .
