---

name: Lint

"on":
  create:
  pull_request:
  push:
    branches: ['*']
  workflow_dispatch:

jobs:

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pipelinecomponents/shellcheck:latest
        with:
          args: /bin/sh test/bin/ci_shellcheck.sh

  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pipelinecomponents/yamllint:latest
        with:
          args: yamllint .
