---
# https://github.com/particleflux/kcov-bats-circleci-codeclimate

name: Test

"on":
  create:
  pull_request:
  push:
    branches: ['*']
  workflow_dispatch:

jobs:

  unit-tests:
    name: BATS
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Run tests
        uses: docker://kcov/kcov:latest
        with:
          args: kcov --include-path src/ codecov/ ./test/bats/bin/bats test/

      # https://github.com/particleflux/kcov-bats-circleci-codeclimate/blob/master/.circleci/config.yml
      - name: Prepare coverage report
        run: |2
          _xml="$(ls -1 codecov/bats*/cobertura.xml | head -1)"
          sed -r \
            's#"bats"#"src"#;s#/github/workspace/##;s#<source>(.+)/</source>#<source>/github/workspace/</source>#' \
            "$_xml" > coverage.xml
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        # https://github.com/SimonKagstrom/kcov/blob/master/doc/codecov.md
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: false

      - uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage.xml
